### ISSUE TITLE
a probelm in 'lukas_kanade.py'

### ISSUE THREAD

**Issue by zhchyang2004** [zhuyifan1993/Direct_RGB-D_SLAM#1]
Hi, 

The coordinate expression seems wrong in Line 18,36 & 37. 

In Line 18, it should be 'np.dot(KInv, np.array([y, x, 1])) ' because Column y is corresponding to horizontal coordinates instead of x.

So, in Line  36&37, it should be as follows accordingly:
interp_I = f((yImg.real.ravel(), xImg.real.ravel())).reshape(I.shape)
interp_D = g((yImg.real.ravel(), xImg.real.ravel())).reshape(D.shape)

Thanks!

**Comment by zhuyifan1993** [comment]
Thanks for reviewing my code and pointing out that mistake! I've updated it.
